### ISSUE TITLE
Destroying a Phaser game instance with noReturn true causes undefined error in navmesh destroy

### ISSUE THREAD

**Issue by smjnab** [mikewesthad/navmesh#10]
If you use noReturn (this.game.destroy(true, true)) to destroy your Phaser 3.20.1 (and earlier), you'll get undefined for this.systems and the m in meshes.forEach( in the destroy method for phaser-navmesh.js (rows 1589 to 1596 in the dist file).

    destroy() {
          this.systems.events.off("boot", this.boot, this);
          const meshes = Object.values(this.phaserNavMeshes);
          this.phaserNavMeshes = {};
          meshes.forEach(m => m.destroy());
          this.scene = undefined;
          this.systems = undefined;
   } 

Thank you for the plugin (and the collision plug as well)!

**Comment by smjnab** [comment]
Sorry, my mistake!

**Comment by mikewesthad** [comment]
No worries! Glad you got it sorted out.
