### ISSUE TITLE
Navmesh interactive demo example (non phaser)

### ISSUE THREAD

**Issue by wini3d** [mikewesthad/navmesh#11]
perhaps more like a suggestion to have a non-phaser example like the [interactive demo](https://www.mikewesthad.com/navmesh/demo/).

**Comment by mikewesthad** [comment]
Happy to accept a pull request for something like that.

The reason why the [node demo](https://github.com/mikewesthad/navmesh/blob/master/packages/examples-node/index.js) for non-phaser environments is so minimal is because it doesn't include any game engine at all as a dependency. That's because I suspect folks using it in a node environment may want to use it for server-side logic.

**Comment by wini3d** [comment]
@mikewesthad I see, would another simple 2d engine like [kontra.js](https://github.com/straker/kontra/) be enough to cover the example demo?

**Comment by mikewesthad** [comment]
Ohhh, I see what you are asking about now. You were hoping to see how to use it with another game engine. I don't know kontra.js, but would be happy to accept a pull request with an example demo. If you want to create it as a [codesandbox](https://codesandbox.io/) or as a gist/repository, we could link to it from the readme. Alternatively, it could be added as a package under "packages/example-kontra." The first option is probably the easiest/quickest to do.

**Comment by wini3d** [comment]
Great, yes that was the idea since I am not yet that familiar with it and trying to use it on a custom or generic 2d engine and kontra seems to be simple enough if it gets integrated with it.

**Comment by Wenish** [comment]
got here something up and running:
https://colyseus-unity3d-navmesh.firebaseapp.com/

Code
creating the navmesh: https://github.com/Wenish/ColyseusNavmeshExample/blob/master/Server/src/utility/loadNavMesh.ts#L30
using the navmesh: https://github.com/Wenish/ColyseusNavmeshExample/blob/master/Server/src/rooms/match/actions/actionUnitMoveTo.ts#L39

**Comment by mikewesthad** [comment]
@Wenish Cool! Thanks for sharing. Does it depend on the server sending some commands to the client for the agent to move? When I load up the client, it just seems to be a sphere sitting there.

**Comment by mikewesthad** [comment]
Nevermind - right click to move! Added to the readme.

**Comment by objectiveSee** [comment]
This demo does not appear to be working any more.
