### ISSUE TITLE
restricted movement

### ISSUE THREAD

**Issue by GGAlanSmithee** [mikewesthad/navmesh#12]
Hi!

Is it possible to add restrictions to the calculated path? I would like to mimic the behaviour of a traditional grid based, 8-directional a-star pathfinding library. That is, the path is limited to 8 directions in discrete chunks of an arbitary sized (say 32x32 pixel) grid.

I know I could use another existing library for this, but I really like this lib and would like to stick to only one pathfinding solution!

Thanks.

**Comment by mikewesthad** [comment]
Hi @GGAlanSmithee - sorry for the delay in responding. I think that'd be a significant modification to the library. The way the library works is that it looks for a path through adjacent polygons. It assumes you can move from one polygon to any of its adjacent neighbors. If the path is restricted to 8 directions, that assumption is no longer true. You'd be better off using a simpler grid-based pathfinding library like easystar.js.

That said, happy to accept a PR if it's something you'd like to explore adding to navmesh.
