### ISSUE TITLE
Can not install navmesh using npm

### ISSUE THREAD

**Issue by kumadam** [mikewesthad/navmesh#19]
Hi,

Here is the log...

C:\Users\serku\Documents\012>npm install --save navmesh
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/mikewesthad/javascript-astar.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\serku\AppData\Roaming\npm-cache\_logs\2020-05-08T08_56_36_346Z-debug.log

**Comment by mikewesthad** [comment]
What version of npm are you using? This works fine in my testing under 6.14.4.

**Comment by kumadam** [comment]
It was 6.13.4(win), I've upgraded it to 6.14.5, result is the same but I think that it is about windows-nmp thing.
By the way 6.14.4(mac) is working. Thanks.

**Comment by mikewesthad** [comment]
If I had to guess, it looks like that error message from the first post is saying that you don't have git installed on your machine (or it is not available in the terminal window you are using).

Glad to hear you got it working.

**Comment by kumadam** [comment]
You're absolutely right, after I fixed the path problem, it worked. Thanks a lot.
