### ISSUE TITLE
Double boot call for phaser plugin

### ISSUE THREAD

**Issue by malahaas** [mikewesthad/navmesh#29]
Phaser calls boot on plugins automatically so the boot call in the phaser-navmesh-plugin causes it to be called twice. this means destroy gets called twice (listener registered twice) and an error is thrown.

Fix here: https://github.com/mikewesthad/navmesh/pull/28

**Comment by mikewesthad** [comment]
Thanks! I'll work on getting this released today. The packages have been overhauled to typescript, so I want to check a few things before I push all those updates into a release.

**Comment by malahaas** [comment]
@mikewesthad np. One thing I thought of last night after I PR'd is that it's possible you had that there due to an older version of Phaser not calling that on plugins. If that's the case (and you want to maintain backwards compatibility) you may want to leave the line I removed and just check an isBooted flag for your plugin within the boot method. /justAThought

**Comment by mikewesthad** [comment]
Yeah, I was wondering about something similar as I was looking at the code. I'll have to take a peek at Phaser's plugin system history to see. I might add an `isBooted` and/or `isDestroyed` flag to make it safe to call `boot` or `destroy` multiple times.
