### ISSUE TITLE
Not compatible with Phaser v3

### ISSUE THREAD

**Issue by cour64** [mikewesthad/navmesh#3]
Hi,

I'm not sure if this is a bug or just a poor setup but no matter what I do I cannot get this imported. I have tried using both a plain script tag from HTML as well as an import using webpack but nothing seems to work. I am getting two errors, the first, from using 

a simple html script tag 
`<script src="dist/phaser-navmesh.min.js"></script>`

as well as a normal require or import from phaser-navmesh
`import { PhaserNavmesh } from "phaser-navmesh";`
`const phaserNavmesh = require('phaser-navmesh');`

all three of these methods of importing produce this error for me in Chrome and Firefox

> Uncaught TypeError: Super expression must either be null or a function, not undefined

Perhaps a more telling error comes from trying to import from the raw es6 library, using 

`import PhaserNavmesh from "phaser-navmesh/src/library";`

produces the following error

> Uncaught TypeError: Class extends value undefined is not a constructor or null

debugging in chrome for this second error takes me to  line 14 of nav-mesh-plugin.js

`class NavMeshPlugin extends Phaser.Plugin {`

it seems that Phaser.Plugin is undefined and this is what is causing the error to be thrown, this leads me to believe that phaser-navmesh doesn't have access to Phaser for some reason but i'm not sure if this is the case.

**Comment by mikewesthad** [comment]
Hey @cour64, which version of Phaser are you trying to use? This was written for v2, though I'm planning on updating it to work with v3 soon. I suspect you are using v3.

**Comment by cour64** [comment]
Hah realised that was probably the issue after I went to bed last night, sorry it was late! Thanks for adding the note to clarify.

**Comment by mikewesthad** [comment]
No worries - thanks for doing all that detective work to diagnose the issue. I'm going to leave this issue open until v3 compatibility is in place.

**Comment by mikewesthad** [comment]
Should be v2 and v3 compatible now - they are separate libraries within the repo. I'm still working on testing and documenting, but if you want to give the v3 nav mesh wrapper a go, you can follow along with:

[packages/examples/main.js](https://github.com/mikewesthad/navmesh/blob/master/packages/examples/src/demo/js/main.js) - sets up the scene plugin in the game's config
[packages/examples/scenes/start.js](https://github.com/mikewesthad/navmesh/blob/master/packages/examples/src/demo/js/scenes/start.js) - scene that uses the plugin for pathfinding
