### ISSUE TITLE
TypeError: NavMesh.buildPolysFromGridMap is not a function

### ISSUE THREAD

**Issue by Wenish** [mikewesthad/navmesh#37]
```ts
import * as NavMesh from 'navmesh'

const gridWidth = 5
const gridHeight = 4
const matrix2d =  new Array(gridHeight).fill(0).map(() => new Array(gridWidth).fill(0));
const meshPolygonPoints = NavMesh.buildPolysFromGridMap<number>(matrix2d)
```

Running this code gives the error:
`TypeError: NavMesh.buildPolysFromGridMap is not a function`

i think something woth the exports dosnt work

**Comment by mikewesthad** [comment]
Ahh, thanks! I think I added that feature but then never created a new publish. I'll take a look today.

**Comment by Wenish** [comment]
very kind of you :)

**Comment by Wenish** [comment]
with navmesh 2.2.1 its still the same problem :(

**Comment by mikewesthad** [comment]
Only after publishing that new release earlier did I realize the root cause is a misconfigured webpack output which only ever grabs the "default" export and ignores the rest of the exports 🤦. Fix is in the works, just testing before publishing.

**Comment by mikewesthad** [comment]
Alright, v2.3.0 should be live now for all the packages with the fixed exports!
