### ISSUE TITLE
add a shrink param to builMeshFromTilemap

### ISSUE THREAD

**Issue by SylvainBreton** [mikewesthad/navmesh#40]
Hi,
First thanks for your plugin.

I just noticed that the buildPolysFromGridMap can take a shrink amount as parameter. However the buildMeshFromTilemaps don't.

It would be very convenient to be able to have this param in buildMeshFromTilemaps

**Comment by mikewesthad** [comment]
Sorry - I've been traveling, so slow to respond to issues this month. Good point, that must have been an oversight. I'll look into it this week.

**Comment by mikewesthad** [comment]
Should be live in the latest (2.3.1)!
