### ISSUE TITLE
Unexpected token when trying to use phaser 3 plugin

### ISSUE THREAD

**Issue by craigharman** [mikewesthad/navmesh#43]
I am getting the following error when importing the plugin:

```
ERROR in ./node_modules/phaser-navmesh/dist/phaser-navmesh-plugin.js 1:4581
Module parse failed: Unexpected token (1:4581)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
Using typescript and webpack. Hope you can help!

**Comment by mikewesthad** [comment]
Hi @craigharman - hmm, could you share a link to your project (or a stripped down version)?

**Comment by craigharman** [comment]
Thanks for your response mike (and your great plugin). I started building a Phaser game from scratch to provide you with an example and it worked, so I upgraded node to latest 14.x and it seems to work now.

**Comment by mikewesthad** [comment]
Woohoo! Glad you got it working
