### ISSUE TITLE
Phaser 3 support is broken

### ISSUE THREAD

**Issue by gnesher** [mikewesthad/navmesh#7]
The example for the Phaser3 plugin no longer works as it seems like the plugin manager has been updated.

**Comment by mikewesthad** [comment]
@gnesher, thanks for the bug report. Could you be more specific? The Phaser 3 plugin examples work as of the latest release, 3.16.2.

**Comment by gnesher** [comment]
Hi @mikewesthad I've tried to follow the example under phaser-navmesh but can't seem to access the plugin. Mind you I'm fairly new to Phaser so I might be missing something.

I'll prepare an example and link it here

**Comment by mikewesthad** [comment]
Great - thanks. I'll take a look whenever you get a chance to link it.

In the meantime, I added a [codesandbox demo](https://codesandbox.io/s/zq1wvozxll?fontsize=14) that shows how to use the library with phaser 3. It's also linked from the readme now.

**Comment by gnesher** [comment]
Thanks for uploading the example - I was able to reproduce it locally.
The thing that confuses me - and I guess this is more to do with Phaser than your plugin is that if I add the following line 
```
  console.log(this.navMeshPlugin.buildMeshFromTiled);
```
to your code example I get an error:
```
Uncaught TypeError: Cannot read property 'buildMeshFromTiled' of undefined
```

**Comment by mikewesthad** [comment]
Really? That logs a function for me.

With CodeSandbox, the default hot module replacement will often error out if you make a change. So if you make a change like adding that `console.log`, you need to hit the refresh button in the browser tab. E.g.

![image](https://user-images.githubusercontent.com/1131802/56813363-5feb7300-6802-11e9-8374-5c37436ecde2.png)
